### ISSUE TITLE
Better Logging Messages

### ISSUE THREAD

**Issue by ethanfrey** [confio/ts-relayer#105]
If you find some bad message, list it here with how to improve... let's try to get to them all some day.

- [x] ics20.ts `Created connections ${conn} (${client}) <=> ${conn} (${client})` should show the chain-id of both sides
- [x] ibcclient.ts - all the debug messages with binary data inside are unreadable... let's base64 encode it and/or truncate any long arrays, so we can see the essential fields (we can manually strip off fields in ibcclient msg before sending to logger)
- [x] When relaying packets or acks, `verbose` level should show the channel and data being sent (maybe sequence?) - if the data is json/utf8 display as text, otherwise as 0x1234 style hex. This will help to observe ics20 packet success/error codes
- [x] All log messages from ibcclient.ts should be prefixed by the chainId (test on verbose)
- [x] Also please use `console.log` (or other output) and *not* the logger for the intended output of the `ibc-setup` commands: https://github.com/confio/ts-relayer/pull/106#pullrequestreview-610538747

**Comment by alpe** [comment]
> verbose: Starting relayer with options {"src":"local_wasm","dest":"local_simapp","home":"/Users/alex/.ibc-setup","mnemonic":"parrot health month then december purpose turkey trim noodle seat curious beauty","srcConnection":"connection-0","destConnection":"connection-0","poll":60,"maxAgeSrc":86400,"maxAgeDest":86400}

Do not log `mnemonic` . Maybe hash it when needed
