### ISSUE TITLE
Enhance ibc-setup init commands

### ISSUE THREAD

**Issue by ethanfrey** [confio/ts-relayer#108]
A few extra flags for `ibc-setup init` that might help in real world use-cases:

- [ ] `copy-from` will take the `registry.yaml` an existing local initialized relayer. This is useful if you have customized it already in one instance and want a second with the same list of custom chains. eg. `ibc-setup --home ~/.relayer2 --copy-from ~/.ibc-setup --src custom-chain-1 --dest other-custom-2`
- [ ] `download-only` which will just create an empty config dir and download the default registry file there. It will abort if there is already a `registry.yaml` file there. The purpose is when we want to customize this before running init.

**Comment by bartmacbartek** [comment]
>copy-from will take the registry.yaml an existing local initialized relayer. This is useful if you have customized it already in one instance and want a second with the same list of custom chains. eg. ibc-setup --home ~/.relayer2 --copy-from ~/.ibc-setup --src custom-chain-1 --dest other-custom-2

I feel like this option can create more confusion than good, but I may be wrong. What happens when I run the second relayer, kill it, modify the registry and rerun the command? Should it overwrite the edited registry?

To confirm, it should copy the **registry.yaml** only, not **app.yaml**, right?

---

`download-only` is similar to `once` option in `ibc-relayer start`, they are both booleans. Should it be possible to set them via environment variables? If yes, what values should they? I suggest:
```bash
RELAYER_DOWNLOAD_ONLY=true
```

**Comment by ethanfrey** [comment]
> I feel like this option can create more confusion than good, but I may be wrong. What happens when I run the second relayer, kill it, modify the registry and rerun the command? Should it overwrite the edited registry?

To confirm, it should copy the registry.yaml only, not app.yaml, right?

`--copy-from` should require an uninitialized destination (like init does in general, right?). It will will copy **registry.yaml** from the `--copy-from` path. It will then create **app.yaml** the normal way. It just replaces "download from github" with "reuse local registry". I am sure you can find a better name. Maybe `--registry-from`?

For both of them the basic purpose is to allow me to add a few new chains to my registry and still use the init commands without having to mess with `rm` `cp` or looking in the internals of `.ibc-setup`. Using this for chains not in github is a major use case. But if you can find a new flow / command that handles that, I am open to it (and please rename all variables if you have a better name)

**Comment by ethanfrey** [comment]
> download-only is similar to once option in ibc-relayer start, they are both booleans. Should it be possible to set them via environment variables? If yes, what values should they?

> RELAYER_DOWNLOAD_ONLY=true

:+1: sounds good

Also, if you think `--download-registry` or some other name is more clear, feel free to adapt. Whatever you end up doing, please add it to the spec of `ibc-setup init` as well

**Comment by ethanfrey** [comment]
Accept `true|1|on|yes` for parsing boolean flags
