### ISSUE TITLE
Persist last queried heights over relayer restart

### ISSUE THREAD

**Issue by ethanfrey** [confio/ts-relayer#110]
Follow up from #104

* Relayer persistently stores last height queried for better performance on startup

Relevant lines of code from `ibc-relayer`:

```ts
async function relayerLoop(link: Link, options: LoopOptions, logger: Logger) {
  // TODO: fill this in with real data on init
  // (how far back do we start querying... where do we store state?)
  let nextRelay = {};
```

On first start, it can query all packets from genesis, which can be slow. It should then persist this state in a file (not app.yaml, but in the same dir). This file is read on restart and is used, so it just queries since the last time it ran.

The file is not meant to be human-readable (just delete it if you want to force scanning all events since forever), and could be stored in JSON rather than YAML if that is easier. 

Also, it would be nice to allow a user to set those values initially even if there is no JSON file. These take presidence over any json file:
* `--scan-from-src <height>` - equivalent to setting `packetHeightA` and `ackHeightA`
* `--scan-from-dest <height>` - equivalent to setting `packetHeightB` and `ackHeightB`

hmm... maybe we should rename those variables in the JSON?

**Comment by bartmacbartek** [comment]
@ethanfrey 

>hmm... maybe we should rename those variables in the JSON?

Could you elaborate more on that, please?

**Comment by ethanfrey** [comment]
We can leave as is.
Just thought `scan-from-src` -> `packetHeightA` there is a `src` / `A` renaming.
