### ISSUE TITLE
Add simapp chain to CI with no IBC connections

### ISSUE THREAD

**Issue by bartmacbartek** [confio/ts-relayer#130]
Add additional chain in the CI with no connections/channels to test parts of the commands which produce different output when operating on a clean chain.

Context: https://github.com/confio/ts-relayer/pull/126#discussion_r595891527

examples of such commands:
- `ibc-setup connections` has a different output when no connections exist
- `ibc-setup channels` has a different output when no channels exist

**Alternative idea**
Should we consider stubbing the ibc client in this case? It means just unit testing (without chain instance involved).

**Comment by ethanfrey** [comment]
This was closes with #102
