### ISSUE TITLE
Add prometheus support (local dev)

### ISSUE THREAD

**Issue by ethanfrey** [confio/ts-relayer#133]
See https://github.com/confio/ts-relayer/blob/main/spec/metrics.md

Let's discuss the desired approach and metrics to collect before starting on this issue.

@alpe and @orkunkl I would appreciate it if you could add any references here to how you would connect a prometheus server and/or which metrics in particular you would like to collect.

**Comment by chengwenxi** [comment]
@ethanfrey @bartmacbartek Hi, As you mentioned in the spec https://github.com/confio/ts-relayer/blob/main/spec/metrics.md, the Prometheus metrics can provide notifications on critical situations, like running low on funds or unusually high errors relaying packets of submitting client update. But it seems that it has not been added yet, is there some related plan?

**Comment by ethanfrey** [comment]
There are no currently plans. The idea was to set up the relayer running between two actually used testnets and get an idea of what metrics would be useful with real experience.

We (at Confio) are running Oysternet as a CosmWasm demo and are happy to connect that to another testnet with active users (or connect two independent testnets). Unfortunately, I am having [trouble finding any such networks](https://github.com/confio/ts-relayer/issues/190#issuecomment-849771117)  to use as demos.

If you know of some connection, that would provide us real-world usage data, without us paying large amounts of ATOM out of pocket, it would be very helpful moving this forward
