### ISSUE TITLE
Use 24 word mnemonic instead of 12 word

### ISSUE THREAD

**Issue by orkunkl** [confio/ts-relayer#136]
cosmos-sdk clients that I have seen so far mostly uses 24 word mnemonics. ts-relayer generates a 12 word mnemonic and this seemed bit inconvenient to me.

**Comment by ethanfrey** [comment]
We should support both currently in the config file. (Please re-open this issue if I am wrong)

Since this mnemonic is stored plain text on the relayer machine, I see no purpose to make this even longer.
