### ISSUE TITLE
"ibc-setup balances" becomes unusable if one registry chain is down

### ISSUE THREAD

**Issue by bartmacbartek** [confio/ts-relayer#152]
**About**
If at least one chain is unreachable, the `ibc-setup balances` command outputs an error (fast-fail).

**Current result**
```
error: connect ECONNREFUSED 35.243.155.86:443 {"stack":"Error: connect ECONNREFUSED 35.243.155.86:443\n    at TCPConnectWrap.
afterConnect [as oncomplete] (node:net:1137:16)","config":{"url":"https://rpc.cosmos.network:443","method":"post","data":"
{\"jsonrpc\":\"2.0\",\"id\":979132555359,\"method\":\"status\",\"params\":{}}","headers":{"Accept":"application/json, text/
plain, */*","Content-Type":"application/json;charset=utf-8","User-Agent":"axios/0.21.1","Content-Length":65},"transformRequest":
[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN",
"maxContentLength":-1,"maxBodyLength":-1},"code":"ECONNREFUSED"}
```

**Expected result**
- should inform about unreachable chain
- should still print balances for other chains

**Comment by ethanfrey** [comment]
Yes, I found this before and forgot to write an issue.

I would just catch that and `logger.error()` a message for all chains that it couldn't connect to.
And then print out normally only the ones it could connect to with a non-zero balance
