### ISSUE TITLE
Broken dependency in 0.1.3

### ISSUE THREAD

**Issue by clockworkgr** [confio/ts-relayer#177]
Just a heads up, https://github.com/confio/ts-relayer/blob/v0.1.3/package.json#L36 @confio/relayer locks this dependency which includes this relative path reference: https://github.com/cosmos/cosmjs/blob/v0.25.0-alpha.2/packages/stargate/src/multisignature.ts#L6 but since the @cosmjs/amino package is not in the dependencies, things break

we've gone around it by including the required deps locked to the same version in our relayer-using project so they're installed/resolved in one place but an updated release using 0.25 would be welcome

**Comment by ethanfrey** [comment]
I believe the import was fixed in main, but not tagged. We definitely need a new release anyway for CosmJS 0.25.

**Comment by bartmacbartek** [comment]
👉 Released in [0.1.4](https://github.com/confio/ts-relayer/releases/tag/v0.1.4).
