### ISSUE TITLE
relayer_test_1 and relayer_test_2 faucets are down

### ISSUE THREAD

**Issue by charleenfei** [confio/ts-relayer#190]
registry.yaml indicates these are still up, this leads to the `ibc-setup init --src relayer_test_1 --dest relayer_test_2` command from the README erroring out (ECONNREFUSED)

**Comment by ethanfrey** [comment]
Thank you for pointing this out.
We shut down those testnets thinking they were only used for internal testing. Forgot we started using them in the README (oops).

We are looking to add two new testnets that will be long-running and have a working faucet we can point to. It was a bit much to run 2 nets just for the relayer.  Is there a new gaia testnet coming out soon? Anyone else?

We have a new cosmwasm testnet out we could use as one endpoint.

**Comment by charleenfei** [comment]
sorry for the late response on this. noted!

**Comment by shahankhatch** [comment]
Currently, a Gaia testnet isn't being planned for the short-term.

**Comment by chengwenxi** [comment]
@ethanfrey IRISnet nyancat testnet is long-running and you can use it.

Exposed ports: https://github.com/irisnet/testnets/tree/master/nyancat
Faucet: https://discord.gg/X6dZZxs3#nyncat-faucet

**Comment by ethanfrey** [comment]
@chengwenxi 

I just added `nyancat` to the registry and updated the readme (in #193) and I managed to connect to nyancat and the relayer created a connection with oysternet and an ics20 channel as well. 

When looking into the send commands, I realized it is based on https://github.com/irisnet/irishub/tree/v0.16.0 which comes from Nov 2020. We only support Cosmos SDK 0.41.1+ in the relayer and I only see problems trying to support a testnet using a pre-release version of ibc. At least in the initial README file.

I am happy to keep it in the registry, but hope for a more "standard" one for the readme.

**Comment by chengwenxi** [comment]
> When looking into the send commands, I realized it is based on https://github.com/irisnet/irishub/tree/v0.16.0 which comes from Nov 2020. We only support Cosmos SDK 0.41.1+ in the relayer and I only see problems trying to support a testnet using a pre-release version of ibc. At least in the initial README file.

It's https://github.com/irisnet/irishub/tree/v1.1.1, which is based on Cosmos SDK v0.42.4.

View version:
```bash
curl http://35.234.10.84:1317/node_info | jq .application_version
```

**Comment by ethanfrey** [comment]
Nice. I was surprised everything was working so well. This explains it.

One last issue, when relaying packets over the channel, I succeed in relaying from oysternet to nyancat, but on the reverse, I get:

```
info: Relay 1 acks from nyancat-8 => oysternet-1
info: Check whether client on oysternet-1 >= height 1380989
error: Caught error:  Query failed with (18): proof is unexpectedly empty; ensure height has not been pruned: invalid request {"stack":"Error: Query failed with (18): proof is unexpectedly empty; ensure height has not been pruned: invalid request\n    at QueryClient.queryRawProof (/home/ethan/js/ts-relayer/node_modules/@cosmjs/stargate/build/queries/queryclient.js:72:19)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"}
info: Sleeping 10 seconds...
```

This worked for setting up a channel, as I queried proofs immediately upon creating them.
Now, I try to relay a packet from many blocks ago and it fails. I assume there is agressive pruning on these nodes?

**Comment by chengwenxi** [comment]
> I assume there is agressive pruning on these nodes?

Yes, you can use another non-pruning node 34.80.202.172, all ports are default value.

**Comment by ethanfrey** [comment]
Merged with this updated node.

I'd appreciate it if you could run through the readme with master or last tagged release and confirm it works for you.

**Comment by chengwenxi** [comment]
> I'd appreciate it if you could run through the readme with master or last tagged release and confirm it works for you.
> Also, I'd gladly add a link to more info on IrisNet/Nyancat for people who want to see those tokens, use real tools to send them, etc.

Follow the readme and everything works well. 👍

**Comment by charleenfei** [comment]
followed the readme as well, works for me!
