### ISSUE TITLE
Ensure we support sdk v0.43 as well

### ISSUE THREAD

**Issue by ethanfrey** [confio/ts-relayer#192]
This seems to have some breaking changes (in events at least... maybe some in protobuf msg?) from 0.42, so the relayer must be smart enough to handle it.

See https://github.com/informalsystems/ibc-rs/issues/918 and https://github.com/informalsystems/ibc-rs/issues/1057

**Comment by ethanfrey** [comment]
We should also favor the `packet_data_hex` attribute (if present) over `packet_data`.

This is only present in `ibc-go`: https://github.com/cosmos/ibc-go/blob/main/modules/core/04-channel/keeper/packet.go#L135

**Comment by ethanfrey** [comment]
This should work with CosmJS 0.27.
We need to test the ibc semantics, maybe add hex_data etc.
Definitely need to update CI script

**Comment by webmaster128** [comment]
Please note that the simapp 0.44 (maybe 0.43 as well) does not include IBC support anymore because the ibc module was removed from the cosmos-sdk repo. So this might require changes to the test setup.

**Comment by ethanfrey** [comment]
Closed by #214 as gaiad v6 is using Cosmos SDK 0.44 and ibcv2
