### ISSUE TITLE
Creating ics20 channel results in "broadcasting transaction failed with code 1 (codespace: undefined)"

### ISSUE THREAD

**Issue by spacepotahto** [confio/ts-relayer#201]
In the process of trying to relay between Sentinel and Osmosis, I run into "broadcasting transaction failed with code 1 (codespace: undefined)". Here are the steps I took:

1) `npm i -g @confio/relayer@main` (on July 2nd 2021)
2) `ibc-setup init`
3) Edited registry.yaml with information for sentinelhub-2 and osmosis-1 chains. It looks like:
```
  sentinelhub-2:
    chain_id: sentinelhub-2
    prefix: sent
    gas_price: 0.1udvpn
    hd_path: m/44'/118'/0'/0/0
    ics20_port: 'transfer'
    rpc:
      - XXX
  osmosis-1:
    chain_id: osmosis-1
    prefix: osmo
    gas_price: 0.0uosmo
    hd_path: m/44'/118'/0'/0/0
    ics20_port: 'transfer'
    rpc:
      - XXX
```
I left out the rpc addresses for privacy. They shouldn't be problematic, as I tried using the hermes relayer with those rpc addresses and that worked fine.
3) Ran `ibc-setup init --src sentinelhub-2 --dest osmosis-1`
4) The generated `app.yaml` looks fine (has src: sentinelhub-2, dest: osmosis-1, and mnemonic. I funded both accounts at the generated mnenomic.
5) Ran `ibc-setup ics20 -v`. Got the following output:
```
verbose: Queried unbonding period {"seconds":2419200}
verbose: Create Tendermint client
verbose: Queried unbonding period {"seconds":1209600}
verbose: Create Tendermint client
info: Connection open init: 07-tendermint-16 => 07-tendermint-34
verbose: Get latest commit
verbose: Get validator set for height 1420077
verbose: Get header for height 1420077
verbose: Get validator set for height 1420073
verbose: Get header for height 1420073
verbose: Update Tendermint client 07-tendermint-34
info: Connection open try: 07-tendermint-34 => 07-tendermint-16 (connection-14)
verbose: Get latest commit
verbose: Get validator set for height 217552
verbose: Get header for height 217552
verbose: Get validator set for height 217545
verbose: Get header for height 217545
verbose: Update Tendermint client 07-tendermint-16
error: Broadcasting transaction failed with code 1 (codespace: undefined). Log: internal
```
5) I then tried `ibc-setup connect -v --log-file ./logtest --stack-trace true` and got the following output:
```
verbose: Queried unbonding period {"seconds":2419200}
verbose: Create Tendermint client
verbose: Queried unbonding period {"seconds":1209600}
verbose: Create Tendermint client
info: Connection open init: 07-tendermint-18 => 07-tendermint-37
verbose: Get latest commit
verbose: Get validator set for height 1420173
verbose: Get header for height 1420173
verbose: Get validator set for height 1420167
verbose: Get header for height 1420167
verbose: Update Tendermint client 07-tendermint-37
info: Connection open try: 07-tendermint-37 => 07-tendermint-18 (connection-16)
verbose: Get latest commit
verbose: Get validator set for height 217643
verbose: Get header for height 217643
verbose: Get validator set for height 217636
verbose: Get header for height 217636
verbose: Update Tendermint client 07-tendermint-18
error: Broadcasting transaction failed with code 1 (codespace: undefined). Log: internal {"stack":"Error: Broadcasting transaction failed with code 1 (codespace: undefined). Log: internal\n    at SigningStargateClient.broadcastTx (/usr/lib/node_modules/@confio/relayer/node_modules/@cosmjs/stargate/build/stargateclient.js:209:19)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"}
```

I also tried ts-relayer v0.1.4, same result.

I realized later that for my usecase I don't actually want to create a new path, and to use an existing channel instead, but anyway the above error probably shouldn't happen.

**Comment by ethanfrey** [comment]
Can you please send me a link to the current version of the code *deployed* for sentinel and osmosis. So I can see what version of the Cosmos SDK they are based on.

**Comment by spacepotahto** [comment]
I see, I'm not sure what Cosmos SDK version they're on, but the Github and binary versions the networks are using currently are:
Sentinel: https://github.com/sentinel-official/hub (version 0.7.0)
Osmosis: https://github.com/osmosis-labs/osmosis (version 1.0.1)

**Comment by ethanfrey** [comment]
Hmmm... both of those projects have forked the SDK. After v0.42.4, so in theory they are compatible. But I have no idea what they changed.

https://github.com/sentinel-official/hub/blob/v0.7.0/go.mod#L23

https://github.com/osmosis-labs/osmosis/blob/v1.0.1/go.mod#L32

Maybe I should make a note that projects that fork the SDK are using the relayer at their own risk. I am happy to investigate more if this happens with un-forked cosmos sdk on both sides.

**Comment by ethanfrey** [comment]
Seems old. Closing
