### ISSUE TITLE
error while setting the IBC , 

### ISSUE THREAD

**Issue by Sandeep-Narahari** [confio/ts-relayer#225]
I was trying to setup the ibc but geting this error , may  i know how to solve this issue

Thank you

`$ ibc-setup init --src oysternet --dest nyancat

Initialized home directory at /home/user/.ibc-setup
Pulled default registry.yaml from remote.
Saved configuration to /home/user/.ibc-setup/app.yaml
Source address: wasm1h9ngw7exhpy369j9c0zw34ltaaje0qtntcms95
Destination address: iaa14nsh99hxeszjnuxh9a28xk7mxqfxjt4scj6lq6
Requesting usponge for oysternet-1...
error: getaddrinfo ENOTFOUND faucet.oysternet.cosmwasm.com {"config":{"url":"https://faucet.oysternet.cosmwasm.com/credit","method":"post","data":"{\"address\":\"wasm1h9ngw7exhpy369j9c0zw34ltaaje0qtntcms95\",\"denom\":\"usponge\"}","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/0.21.4","Content-Length":75},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false}},"code":"ENOTFOUND"}`

**Comment by ethanfrey** [comment]
Yeah, oyster net is long gone. I have updated master with newer networks in #230
