### ISSUE TITLE
Make configurable fees for the ibc transactions

### ISSUE THREAD

**Issue by ethanfrey** [confio/ts-relayer#23]
In `ibcclient.ts` I created a prebuilt fee table with hardcoded values 

```ts
// TODO: replace this with buildFees in IbcClient constructor to take custom gasPrice, override gas needed
const fees = {
  initClient: {
    amount: coins(2500, 'ucosm'),
    gas: '100000',
  },
  // ...
};
```

We should:

1. Allow these to be configurable in IbcClient, like the other options on SigningStargateClient. They can be a separate member of Options for just the ibc-related default gas if that is easier way to extend the options.
2. Provide sensible default gas for each transaction - take the current values and see if you can lower them a bit
3. Store the values in IbcClient and use them (remove the global fees object)

**Comment by willclarktech** [comment]
Closed in #32
