### ISSUE TITLE
Restore Browser Compatibility

### ISSUE THREAD

**Issue by mccallofthewild** [confio/ts-relayer#266]
Versions >v0.4.0 are not browser compatible. 

Trust assumptions are non-fungible for contracts on permissionless chains, and self-relaying is the most obvious solution. 

See: 
* https://github.com/DA0-DA0/dao-dao-ui/issues/885
* https://github.com/game-of-nfts/gon-evidence/issues/479

**Comment by webmaster128** [comment]
Hey @mccallofthewild, it's a lot of text in the linked issues.

What exactly is not working in browsers that is working in node.js? What do you do? What errors do you have?

**Comment by webmaster128** [comment]
If there is anything wrong with browser support, please create a specific issue with details of the problem. In general, it is expected that ts-relayer works in browsers. Closing for now.
