### ISSUE TITLE
Add Channel setup functionality

### ISSUE THREAD

**Issue by ethanfrey** [confio/ts-relayer#54]
Builds on #53 

The following just need the registry (should work if mnemonic is not provided):

* Implement `ibc-setup ports --chain=ABC`
* Implement `ibc-setup connections --chain=ABC`
* Implement `ibc-setup channels --chain=ABC [--port=transfer]`

The following needs the mnemonic as well, and will reuse an existing connection via `Link.createWithExistingConnections`

* Implement `ibc-setup channel --src=ABC --dest=XYZ --src_connection=connection-3 --dest_connection=connection-4 ...`

(All commands [defined in spec](https://github.com/confio/ts-relayer/blob/main/spec/ibc-setup.md#channel-setup))

Please add a test: create connection as in #53, query channels with nothing, make new channel on existing connection, query channels that it is there

**Comment by bartmacbartek** [comment]
`ibc-setup channels --chain=ABC [--port=transfer]` (point 3) is merged via https://github.com/confio/ts-relayer/pull/97 but it still lacks tests
