### ISSUE TITLE
Revisit spec of app.yaml and cli interaction

### ISSUE THREAD

**Issue by ethanfrey** [confio/ts-relayer#98]
app.yaml is a nice convenience and allows us to store all state.

A number of script will "auto-update" it for you as well. Which can lead to undesired behavior if you are using some values from CLI and some from app.yaml.

This was brought up a few times in comments:

* https://github.com/confio/ts-relayer/pull/95/files#r590706164
* https://github.com/confio/ts-relayer/pull/95/files#r590707249
* https://github.com/confio/ts-relayer/pull/94#discussion_r589218696

We need to rethink the approach and adjust the spec. Then update the implementations to match.

**Comment by ethanfrey** [comment]
The *relayer* should **not** modify `app.yaml` every. This is the one that really should be steered by command line flags or env variables - those are much simpler to setup in systemd files, as they are in the same file where you set the command.

The `registry.yaml` always needs to be on disk (too much info).

For `ibc-setup`, let's see what makes sense. If a value is in `app.yaml` we should (1) not allow an override and/or (2) not overwrite the file

**Comment by bartmacbartek** [comment]
Would it make sense to detect if the value exists in the `app.yaml`, if yes, then ask the user if it should be overwritten.

Alternatively, we could not overwrite values by default and print appropriate info such as
>Values in app.yaml for properties xxx, yyy, already exist. Pass --overwrite flag to overwrite them while using ibc-setup commands.

**Comment by ethanfrey** [comment]
> Would it make sense to detect if the value exists in the `app.yaml`, if yes, then ask the user if it should be overwritten.
> 
> Alternatively, we could not overwrite values by default and print appropriate info such as
> 
> > Values in app.yaml for properties xxx, yyy, already exist. Pass --overwrite flag to overwrite them while using ibc-setup commands.

In general, Iike the idea. Note, I would use `--force` instead of `--overwrite` as it is more common term (and I know that using it may break things and puts the burden on me)

To clarify, there are 5 cases:

* Only in `app.yaml`: use the value
* Only in CLI or env (or both): use the value and save it in `app.yaml`
* In neither: return error "source chain required" or such
* In both:
  * `--force` not present, then return error "Values in app.yaml...." which you posted above
  * `--force` present, then use the value from CLI/env and update `app.yaml` with that. This may break something (like change the chain id in the `app.yaml` so it no longer works with the old path)

I would only accept `--force` as a CLI arg, not from env or `app.yaml`

**Comment by ethanfrey** [comment]
We all agree on this:

* Only in `app.yaml`: use the value
* Only in CLI or env (or both): use the value and save it in `app.yaml`
* In neither: return error "source chain required" or such

The open question is how to best handle the "both" case. Which may or may not be what I wrote above.
Current implementation works like `--force` is always passed.

**Comment by ethanfrey** [comment]
Current implementation is dangerous.
I propose we just now implement the non `--force` mode, return error as above:

"Values in app.yaml for properties xxx, yyy, already exist. If you really want to change chain_id or connection, come to discord for help and help us improve the UX"

The setup tool will error before setting up any client/channel. 

We can add a `--force` variant (maybe like above), once some users request it and they define their use cases and expectations.

**Comment by ethanfrey** [comment]
TODO: make issue/PR - don't dump stack trace on error. Maybe add an eg `--trace` flag to dump this if you really want (for debugging). Or maybe just enable this with `--log-level=debug`. Whatever makes the most sense
